---

{{ if .Values.paws.frontPageEnabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    name: paws-front-page
    ingress.paws.wmcloud.org: front
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: {{ .Values.paws.ingress.frontRedirect | quote }}
  name: paws-front-page
spec:
  rules:
    - host: {{ .Values.paws.ingress.frontHost | quote }}
{{ end }}
