{{ if .Values.localdev.enabled }}
# We assume this is only enabled in a local dev environment, so...
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: userhomes
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/project/paws/userhomes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dumps1
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/nfs/dumps-clouddumps1001.wikimedia.org
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dumps2
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/nfs/dumps-clouddumps1002.wikimedia.org
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: dumps
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/public/dumps
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scary-host-vol-perm-fix
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ printf "permission-fix-%s" .Release.Name | quote }}
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: fixingperms-host-vols
          image: {{ tpl .Values.localdev.image.template . | quote }}
          command:
            - chown
            - -R
            - 52771:52771
            - /data/project/paws/userhomes
          volumeMounts:
            - mountPath: /data/project/paws/userhomes
              name: security-disaster-only-for-minikube
      volumes:
        - name: security-disaster-only-for-minikube
          hostPath:
            path: /mnt/project/paws/userhomes
{{ end }}
