---

{{ if .Values.pawsPublicEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paws-public
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: nbserve
  name: nbserve
spec:
  replicas: {{ .Values.pawspublic.nbserve.replicas }}
  selector:
    matchLabels:
      name: nbserve
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: nbserve
    spec:
      serviceAccount: paws-public
      containers:
        - image: {{ tpl .Values.pawspublic.nbserve.image.template . | quote }}
          imagePullPolicy: Always
          name: nbserve
          ports:
            - containerPort: 8000
              name: nbserve
              protocol: TCP
          volumeMounts:
            - mountPath: /data/project/paws/userhomes
              name: pawshomes
          resources:
            requests:
              memory: "2000Mi"
              cpu: "50m"

      volumes:
{{ if .Values.localdev.enabled }}
        - hostPath:
            path: /srv/misc/shared/paws/project/paws/userhomes
{{ else }}
        - nfs:
{{- with (index .Values.jupyterhub.hub.extraVolumes 0) }}
            server: {{ .nfs.server }}
{{- end }}
            path: /srv/misc/shared/paws/project/paws/userhomes
{{ end }}
          name: pawshomes
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: renderer
  name: renderer
spec:
  selector:
    matchLabels:
      name: renderer
  template:
    metadata:
      labels:
        name: renderer
    spec:
      serviceAccount: paws-public
      containers:
        - env:
            - name: BASE_PATH
              value: /data/project/paws/userhomes/
            - name: URL_PREFIX
              value: /
          image: {{ tpl .Values.pawspublic.renderer.image.template . | quote }}
          imagePullPolicy: Always
          name: renderer
          ports:
            - containerPort: 8000
              name: nbserve
              protocol: TCP
          volumeMounts:
            - mountPath: /data/project/paws/userhomes
              name: pawshomes
          resources:
            requests:
              memory: "1000Mi"
              cpu: {{ .Values.pawspublic.renderer.cpu }}
      volumes:
{{ if .Values.localdev.enabled }}
        - hostPath:
            path: /srv/misc/shared/paws/project/paws/userhomes
{{ else }}
        - nfs:
{{- with (index .Values.jupyterhub.hub.extraVolumes 0) }}
            server: {{ .nfs.server }}
{{- end }}
            path: /srv/misc/shared/paws/project/paws/userhomes
{{ end }}
          name: pawshomes
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: renderer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: renderer
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 200
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: paws-public
  name: paws-public
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    name: nbserve
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: renderer
  name: renderer
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    name: renderer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    name: paws-public-custom
    ingress.paws.wmcloud.org: public
  annotations:
  name: paws-public-custom
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.pawspublic.ingress.host | quote }}
      http:
        paths:
          - backend:
              service:
                name: paws-public
                port:
                  number: 8000
            pathType: Prefix
            path: /
{{ end }}
