#!/bin/bash

echo "
install.packages(c('crayon', 'pbdZMQ', 'devtools'), repos = c('http://cran.us.r-project.org'))
devtools::install_github(paste0('IRkernel/', c('repr', 'IRdisplay', 'IRkernel')))

IRkernel::installspec(FALSE)
" > /tmp/install-r

R -f /tmp/install-r

rm /tmp/install-r
