#!/bin/bash

echo "
install.packages(
    c('rzmq','repr','IRkernel','IRdisplay', 'devtools', 'dplyr', 'curl', 'ggplot2', 'RMySQL'),
    repos = c('http://irkernel.github.io/', 'http://cran.us.r-project.org'),
)

IRkernel::installspec(FALSE)
" > /tmp/install-r

R -f /tmp/install-r

rm /tmp/install-r
