#!/bin/bash

virtualenv -p python3 /srv/paws

# Upgrade pip to support conditionals in requirements.txt
/srv/paws/bin/pip install -U pip

# Remove 'Pillow' from requirements.txt
sed -e '/Pillow/d' /srv/paws/requirements.txt > /tmp/requirements.txt

/srv/paws/bin/pip install --no-cache-dir -r /tmp/requirements.txt
/srv/paws/bin/pip install --no-cache-dir -r /srv/paws/dev-requirements.txt

# cleanup
rm /tmp/requirements.txt
