#!/bin/bash
pip install --no-cache-dir \
	 pythreejs \
	 ipyleaflet \
	 bqplot \
	 git+https://github.com/yuvipanda/nbresuse.git


jupyter nbextension enable --py widgetsnbextension --system
jupyter nbextension enable --py ipyleaflet --system
jupyter nbextension enable --py bqplot --system
jupyter nbextension enable --py pythreejs --system
jupyter serverextension enable --py nbresuse --system
jupyter nbextension enable --py nbresuse --system
