#!/bin/bash

virtualenv -p python3 /srv/pwb

# Upgrade pip to support conditionals in requirements.txt
/srv/pwb/bin/pip install -U pip

# Remove 'Pillow' from requirements.txt
sed -e '/Pillow/d' /srv/pwb/requirements.txt > /tmp/requirements.txt

/srv/pwb/bin/pip install -r /tmp/requirements.txt
/srv/pwb/bin/pip install -r /srv/pwb/dev-requirements.txt

# cleanup
rm /tmp/requirements.txt
