---

mysql:
  domain: analytics.db.svc.eqiad.wmflabs
  # TODO: remove this when the multiinstance replica proxy is removed
  host: enwiki.analytics.db.svc.eqiad.wmflabs
jupyterhub:
  hub:
    extraVolumes:
      - name: homes
        nfs:
          server: nfs-tools-project.svc.eqiad.wmnet
          path: /srv/misc/shared/paws/project
      - name: dumps
        nfs:
          server: clouddumps1002.wikimedia.org
          path: /
      # Without this, dumps becomes inaccessible and can hang the host
      - name: dumps-src1
        nfs:
          server: clouddumps1001.wikimedia.org
          path: /
      - name: dumps-src2
        nfs:
          server: clouddumps1002.wikimedia.org
          path: /
    extraConfig:
      00-myConfig: |
          localdev = False
          nfs_home = 'nfs-tools-project.svc.eqiad.wmnet'
          dumps_src1 = 'clouddumps1001.wikimedia.org'
          dumps_src2 = 'clouddumps1002.wikimedia.org'
    db:
      type: mysql
      upgrade: true
  ingress:
    enabled: true
    hosts:
      - hub-paws.wmcloud.org
    annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_input_headers "REFERER: http://hub-paws.wmcloud.org/hub/";
  singleuser:
    extraEnv:
      HUB_DOMAIN: "hub-paws.wmcloud.org"  # Check jupyterhub.ingress.hosts
minesweeper:
  enabled: true
localdev:
  enabled: false
pawspublic:
  nbserve:
    requests:
      memory: "2000Mi"
  ingress:
    host: public-paws.wmcloud.org
  renderer:
    requests:
      cpu: "500m"
      memory: "1000Mi"
