---

mysql:
  domain: analytics.db.svc.eqiad.wmflabs
  # TODO: remove this when the multiinstance replica proxy is removed
  host: enwiki.analytics.db.svc.eqiad.wmflabs
dbProxy:
  image:
    tag: latest
jupyterhub:
  hub:
    db:
      type: mysql
      upgrade: true
  ingress:
    enabled: true
    hosts:
      - hub.paws.wmcloud.org
  singleuser:
    extraEnv:
      HUB_DOMAIN: "hub.paws.wmcloud.org"  # Check jupyterhub.ingress.hosts
      REFINE_DOMAIN: "hub.paws.wmcloud.org"
minesweeper:
  enabled: true
localdev:
  enabled: false
pawspublic:
  ingress:
    host: public.paws.wmcloud.org
  renderer:
    cpu: "500m"
