#!/bin/bash

# Make history more useful and permanent!
# Stolen from http://mywiki.wooledge.org/BashFAQ/088
shopt -s histappend
HISTFILESIZE=400000000
HISTSIZE=10000
PROMPT_COMMAND="history -a"

# PS1
PS1='${JPY_USER}@PAWS:\w$ '

echo "Welcome to PAWS!"
echo "Please behave responsibly"
echo "Getting Started: https://www.mediawiki.org/wiki/Manual:Pywikibot/PAWS"
echo "Questions? Need help? Find us on #wikimedia-cloud on IRC on freenode!"
echo "File bugs at https://phabricator.wikimedia.org/maniphest/task/create/?projects=PAWS"
