#!/bin/bash
set -e

echo "
install.packages(c('repr', 'IRdisplay', 'evaluate', 'crayon', 'pbdZMQ', 'devtools', 'uuid', 'digest'), repos = c('http://cran.us.r-project.org'))
devtools::install_github('IRkernel/IRkernel')

IRkernel::installspec(FALSE)
" > /tmp/install-r

R -f /tmp/install-r

# What do you mean, 'isolated environment'?
chown -R ${NB_USER}:${NB_USER} /usr/local/lib/R/site-library

rm /tmp/install-r
