#!/bin/bash
set -euo pipefail

pip install --no-cache-dir \
    pythreejs \
    ipyleaflet \
    bqplot \
    RISE \
    py-heat-magic \
    jupyter-resource-usage \
    git+https://github.com/toolforge/nbpawspublic@main \


jupyter nbextension install --py nbpawspublic --sys-prefix
jupyter nbextension enable --py nbpawspublic --sys-prefix

pip install --no-cache-dir git+https://github.com/toolforge/ipynb-paws@147bbeb4dda35e
