#!/usr/bin/env bash

# from: https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/julia/image/install-julia.bash
set -euo pipefail

export JULIA_PATH=/srv/julia/
export JUPYTER_DATA_DIR=${VENV_DIR}/share/jupyter/

curl --silent --location --fail https://julialang-s3.julialang.org/bin/linux/x64/1.10/julia-1.10.2-linux-x86_64.tar.gz | tar xvz -C ${JULIA_PATH} --strip-components=1
julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.build("IJulia"); using IJulia; installkernel("Julia");'
