#!/bin/bash
#set -euo pipefail
# we're getting closer to the end of life for setup.py pipefail now fails on it.
# To keep labpawspublic working we should update to use wheel

pip install --no-cache-dir \
    pythreejs \
    ipyleaflet \
    bqplot \
    RISE \
    py-heat-magic \
    jupyter-resource-usage \
    git+https://github.com/toolforge/labpawspublic@10ba684789ff5b6e0e2e2122ce68be101266acb8 \
#    git+https://github.com/toolforge/paws-favicon@v1.0 \

# Rebuild JupyterLab for plotly-dash extension
# Should be fixed by https://github.com/plotly/jupyter-dash/issues/49
jupyter lab build

pip install --no-cache-dir git+https://github.com/toolforge/ipynb-paws@147bbeb4dda35e
