#!/bin/bash
set -e

# Remove 'Pillow' from requirements.txt
sed -e '/Pillow/d' /srv/paws/pwb/requirements.txt > /tmp/requirements.txt

# To prevent breakage on older python
/srv/paws/bin/pip install --no-cache-dir -U pip setuptools wheel

/srv/paws/bin/pip install --no-cache-dir -r /tmp/requirements.txt
/srv/paws/bin/pip install --no-cache-dir -r /srv/paws/pwb/dev-requirements.txt
/srv/paws/bin/pip install --editable /srv/paws/pwb

# cleanup
rm /tmp/requirements.txt
