---

{{- if .Values.maintainDumpsNfs.enabled -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: maintain-dumps-nfs
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: maintain-dumps-nfs
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: maintain-dumps-nfs
roleRef:
  kind: Role
  name: maintain-dumps-nfs
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: maintain-dumps-nfs
{{- end }}
