name: Test

on:
  workflow_run:
    workflows: ["preflight testing"]
#      - preflight testing
    types:
      - completed

jobs:
  test-job:
    name: Test Step
    runs-on: ubuntu-latest
    steps:
      - run: env
