name: build

on:
  pull_request:
    paths:
      - images/singleuser/


jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: images/singleuser
          tags: quay.io/wikimedia-paws-beta/singleuser:latest