---

name: "helm-lint"

'on':
  pull_request:

jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build helm-lint container
        run: |
          docker build -f tests/helm-lint/Dockerfile -t helm-lint:01 .
      - name: run helm-lint container
        run: |
          docker run helm-lint:01
