---

name: "PR Notification"

'on':
  pull_request:
    types: [opened, closed]

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify on IRC
    steps:
      - name: irc notification
        run: |
          sudo apt-get update
          sudo apt-get install netcat -y
          message="${{ github.actor }} ${{ github.event.action }} ${{ github.event.pull_request._links.html.href }}"
          echo -e "USER notefromgithub notefromgithub notefromgithub :notefromgithub\nNICK notefromgithub\nJOIN #wikimedia-cloud-feed\nPRIVMSG #wikimedia-cloud-feed :${message}\nQUIT\n" | nc irc.libera.chat 6667
