name: build and push jobber

on:
  pull_request_target:
    paths:
      - images/jobber/**

jobs:
  build-and-push:
    name: build and push jobber
    uses: toolforge/github-actions/.github/workflows/build-and-push.yaml@build-and-push-v2
    with:
      imagename: jobber
    secrets:
      quay_user: ${{ secrets.QUAY_USER }}
      quay_password: ${{ secrets.QUAY_PASSWORD }}
