name: build and push paws-hub

on:
  pull_request_target:
    paths:
      - images/paws-hub/**

jobs:
  build-and-push:
    name: build and push paws-hub
    uses: toolforge/github-actions/.github/workflows/build-and-push.yaml@build-and-push-v2
    with:
      imagename: paws-hub
    secrets:
      quay_user: ${{ secrets.QUAY_USER }}
      quay_password: ${{ secrets.QUAY_PASSWORD }}
