name: build and push renderer

on:
  pull_request_target:
    paths:
      - images/renderer/**

jobs:
  build-and-push:
    name: build and push renderer
    uses: toolforge/github-actions/.github/workflows/build-and-push.yaml@build-and-push-v2
    with:
      imagename: renderer
    secrets:
      quay_user: ${{ secrets.QUAY_USER }}
      quay_password: ${{ secrets.QUAY_PASSWORD }}
