name: build and push singleuser

on:
  pull_request_target:
    paths:
      - images/singleuser/**


jobs:
  build-and-push:
    name: build and push singleuser
    uses: toolforge/github-actions/.github/workflows/build-and-push.yaml@build-and-push-v2
    with:
      imagename: singleuser
    secrets:
      quay_user: ${{ secrets.QUAY_USER }}
      quay_password: ${{ secrets.QUAY_PASSWORD }}
