---

name: "tox"

'on':
  pull_request:

jobs:
  docker-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build tox container
        run: |
          docker build -f tests/tox/Dockerfile -t tox:01 .
      - name: run tox container
        run: |
          docker run tox:01
