---

name: update container tags and Chart.yaml

'on':
  pull_request_target:

jobs:
  update-container-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: git fetch
        run: |
          git fetch
      - name: git checkout
        run: |
          git checkout ${{ github.head_ref }}

      # compare  to upstream main branch
      - name: git add remote
        run: |
          git remote add toolforgepaws https://github.com/toolforge/paws.git
      - name: git remote update
        run: |
          git remote update

      - name: update values.yaml
        run: |
          for i in renderer nbserve paws-hub jobber singleuser minesweeper ; do
            if [[ $(git diff remotes/toolforgepaws/main -- images/${i}/) ]]; then
            sed -i "s/tag: .* # ${i} tag managed by github actions$/tag: pr-${{ github.event.number }} # ${i} tag managed by github actions/" paws/values.yaml
            fi
          done

      - name: update Chart.yaml
        run: |
          # Update Chart.yaml version if something in paws/* has changed. Though only do it once.
          # The grep tests to see if the version has already changed in Chart.yaml
          if [[ $(git diff remotes/toolforgepaws/main -- paws/) ]] && [[ ! $(git diff remotes/toolforgepaws/main -- paws/Chart.yaml | grep ^+version) ]]; then
            VERSION=$(grep ^version paws/Chart.yaml | perl -ne '$_ =~ /^version: (\d+.\d+.)(\d+)/; $version = $2 + 1; print "$1$version"')
            sed -i "s/^version: .*/version: ${VERSION} # patch number managed by github actions/" paws/Chart.yaml
          fi


      - uses: EndBug/add-and-commit@v7
        with:
          add: '["paws/values.yaml", "paws/Chart.yaml"]'
          author_name: Github Action
          author_email: auto@github.com
          branch: ${{ github.head_ref }}
          message: 'auto update of tags and Chart version'
          pull: --rebase --autostash
